### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by apizzuto** [NIFTy-PPL/NIFTy#14]
There is a broken link that 404s for me in the README where it reads `For a quick start, you can browse through the [informal introduction](https://ift.pages.mpcdf.de/nifty/user/code.html) or dive into NIFTy by running one of the demonstrations, e.g.:`

The link: https://ift.pages.mpcdf.de/nifty/user/code.html

Part of https://github.com/openjournals/joss-reviews/issues/6593

**Comment by Edenhofer** [comment]
That's bad :|  #19 should fix this. Thanks for the report!
