### ISSUE TITLE
Please add contribution instructions

### ISSUE THREAD

**Issue by apizzuto** [NIFTy-PPL/NIFTy#15]
As part of https://github.com/openjournals/joss-reviews/issues/6593:

The review asks: `Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support`. You all list (2) and (3) but it was not clear to me if there were contribution instructions

**Comment by Edenhofer** [comment]
Thanks for filing this issue. All kinds of contributions are welcome and we now provide a brief description on how to get started.
