### ISSUE TITLE
Missing DOIs for references

### ISSUE THREAD

**Issue by Abinashbunty** [NIFTy-PPL/NIFTy#22]
Hi authors. This issue is part of my ongoing review in openjournals/joss-reviews#6593 

When running the checks for the references, the bot throws warnings for the following references. I have gathered the DOIs for most except some software based references. Feel free to have a look into it. 😄 

- Physics of the Interstellar and Intergalactic Medium: https://doi.org/10.2307/j.ctvcm4hzr
- The Pan-STARRS1 Surveys: https://doi.org/10.48550/arXiv.1612.05560
- Variational Inference with Normalizing Flows: https://doi.org/10.48550/arXiv.1505.05770
- The No-U-Turn Sampler: Adaptively Setting Path Lengths in Hamiltonian Monte Carlo: https://doi.org/10.48550/arXiv.1111.4246
- Equinox: neural networks in JAX via callable PyTrees and filtered transformations : https://doi.org/10.48550/arXiv.2111.00254
- Efficient and Modular Implicit Differentiation: https://doi.org/10.48550/arXiv.2105.15183
- Scalable Variational Gaussian Process Classification: https://doi.org/10.48550/arXiv.1411.2005
- GPflow: A Gaussian Process Library Using Tensorf: https://doi.org/10.48550/arXiv.1610.08733
- Pyro: Deep Universal Probabilistic Programming: https://doi.org/10.48550/arXiv.1810.09538
- NIFTY: A versatile Python library for signal inference: https://doi.org/10.1051/0004-6361/201321236
- Re-Envisioning Numerical Information Field Theory (NIFTy): A Library for Gaussian Processes and Variational Inference: https://doi.org/10.48550/arXiv.2402.16683

**Comment by Edenhofer** [comment]
Many thanks for going through the trouble of finding all the DOIs! I'm currently on vacation without my laptop until the the end of next week but I'll incorporate the DOIs right afterwards.

**Comment by Edenhofer** [comment]
Thanks for DOIs! I fixed most of them but left some of them as is since the DOIs are references to the arXiv paper and not the journal publication. Unfortunately, some of the ML journals/conferences don't issue DOIs and hence these publications then don't have any even if their corresponding arXiV paper has one.

**Comment by Edenhofer** [comment]
@Abinashbunty Are you ok with not adding DOIs to arXiv if the work is published in a journal and technically doesn't have a DOI?

**Comment by Edenhofer** [comment]
@Abinashbunty Are you happy with this logic of adding DOIs or do you see a better avenue here? In case of the former, could you please confirm in the NIFTy JOSS review that you are okay with it.

**Comment by Abinashbunty** [comment]
Hi @Edenhofer It is fine by me. 👍🏻 I know the references should be some journal at least and also verified that they are indeed published but don't have a DOI. I just wanted to make sure the bot doesn't complain. 

Nevertheless, I approve. 😄

**Comment by Edenhofer** [comment]
Perfect! Thank you for your quick response!
