### ISSUE TITLE
Recommended energy delta

### ISSUE THREAD

**Issue by fmkroci** [NIFTy-PPL/NIFTy#35]
Hello,

I noticed that in your jft demos you couple the energy delta for the linear sampling with the  energy delta used for stopping the KL optimization.

Could you elaborate on these values?
I played around with a simulation study and found very similar values that work well, so I was wondering if there is a good reason.

Thanks in advance!

**Comment by Edenhofer** [comment]
Sure! Roughly speaking the energy potentials for drawing a sample and optimizing the KL are equivalent under some approximations. You can see the similarity if you write down the linearized KL cost potential (start without samples) and the effective optimization function for drawing a sample. You will notice that to first order both look very similar if not identical. For a perfectly linear Gaussian measurement process the similarity is the closest.

Utilizing this insights, we can couple both optimizations. However, to properly equate both optimizations we also have to consider the use of the samples in the KL cost potential. In the cost potential the samples are added to the to-be-optimized parameter vector and in a way dictate the accuracy the accuracy with which we can optimize the KL. The accuracy of the samples specify the point at which they become dominated by noise. As to not constrain the KL minimization, samples should be sampled more accurately than our KL optimization objective, hence, the more stringent minimization criterion for the sampling in the demonstration script.

Putting both together we can advertise a sane default in the demonstration scripts that effectively reduce the number of parameters that the user needs to set manually. While all of this is well motivated, at the end of the day, it remains a heuristic and potentially does not hold for the various inference problems that users tackle. Thus, we still leave the choice open to the user. However, we believe the demonstrations scripts are a very good starting point for most problems.

I hope this clarifies the relation. Please let me know whether anything is still unclear.

**Comment by fmkroci** [comment]
Thanks a lot for the detailed answer!

I tried some limited tests with this heuristic and it seems to work great for my fits.
