### ISSUE TITLE
Gauss-Makrov on GPU

### ISSUE THREAD

**Issue by phaim** [NIFTy-PPL/NIFTy#6]
The the loop in the general gm-process introduced in [this](https://github.com/NIFTy-PPL/NIFTy/commit/6741c295f640f50f18587f00d9e4dfd468fe987e) commit leads to significant performance degradation of the correlated field on the GPU. This seems to be caused by [this loop](https://github.com/NIFTy-PPL/NIFTy/blob/NIFTy_8/src/re/gauss_markov.py#L70). A potential fix could be to implement a specialized function where it is changed to a `cumsum` and use that function in the correlated field.

**Comment by Edenhofer** [comment]
@ph-frank Can you take care of this?

**Comment by ph-frank** [comment]
Fixed. See Merge request  ift/nifty!927
